# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90a1c50390c14dc841e841731d70e93ce295fba948d991828ad379f26cabcfa506620447e24672220bed6280fb78913604d20c71d8b96cd3c47c840aa66a4c2a

test:
  secret_key_base: 79f64355dab133529bdd10299dbc1ec3c967db197607940d0e6b5440fbed04cb675031ec89b107ff47c604c15ee9b0ed353c140d4aa47249ace3f587a0ba130c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
